spring:
  application:
    name: nexus-pm-backend
  main:
    allow-circular-references: true
  
  # H2 Database for testing
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          auto: create-drop
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: false
  
  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8080
  servlet:
    context-path: /api

# Custom application properties
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789mySecretKey123456789}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  
  auth:
    redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:3000/auth/callback}
  
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:3001"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
