spring:
  application:
    name: nexus-pm-backend
  main:
    allow-circular-references: true
  
  # H2 Database for testing (temporarily replacing PostgreSQL)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          auto: create-drop
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: false
  
  sql:
    init:
      mode: never
      continue-on-error: true
  
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false

# Custom application properties
app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:3001"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
  
  file:
    upload-dir: ./uploads
    max-size: 10MB

logging:
  level:
    com.nexuspm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
