spring:
  application:
    name: nexus-pm-backend
  main:
    allow-circular-references: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  # redis:
  #   host: localhost
  #   port: 6379
  #   timeout: 2000ms
  
  # elasticsearch:
  #   uris: http://localhost:9200
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Custom application properties
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789mySecretKey123456789}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:3001"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
  
  file:
    upload-dir: ./uploads
    max-size: 10MB

logging:
  level:
    com.nexuspm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
